FlowingCode/GoogleMapsAddon

assembly/assembly.xml
pom.xml
src/test/java/com/flowingcode/vaadin/addons/DemoLayout.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/DemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/test/LayoutTest.java

Added demo layout.
Upgraded Vaadin version to 14.4.0.

Demo layout

---

assembly/assembly.xml
pom.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/Icon.java
src/test/java/com/flowingcode/vaadin/addons/DemoLayout.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/DemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/test/LayoutTest.java

License header

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/Markers.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

Added some default markers colored

---

src/test/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

Fixes [https://github.com/FlowingCode/AddonsDemoV14/issues/28#issuecomment-725432854](https://github.com/FlowingCode/AddonsDemoV14/issues/28#issuecomment-725432854)

Fix. Added github link in DemoView class

---

pom.xml
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

https://github.com/FlowingCode/AddonsDemoV14/issues/31

Update commons-demo dependency to 2.1.0-SNAPSHOT

---

src/test/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

Fix setItems() incompatibility with Vaadin 18

test(demo): set data provider to combobox

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapsDemo.java

Add click events

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java

GoogleMapClickEvent and GoogleMapRightClickEvent have both the same properties
Proposed by @javier-godoy in [this reply](https://github.com/FlowingCode/GoogleMapsAddon/pull/20#issuecomment-755492749)

refactor: use GoogleMapClickEvent for both right and left click events 

---

assembly/assembly.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/Icon.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/LatLon.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/Markers.java
src/test/java/com/flowingcode/vaadin/addons/DemoLayout.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/DemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/test/LayoutTest.java

Client dependency update, formating and assembly updates.

Google maps client dependency update

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java

fix: fix setting draggable flag on element

---

pom.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/resources/META-INF/resources/frontend/googlemaps/geolocation.js
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GeolocationDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

Geolocation

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

feat: add latitute and longitude data to GoogleMapPolygonClickEvent

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java

fix: fix marker's setters and getters to use element properties

---

pom.xml
src/test/java/com/flowingcode/vaadin/addons/googlemaps/AbstractGoogleMapsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/AddMarkersDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/AddPolygonsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GeolocationDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapsDemo.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java

Demo refactor

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java

fix: fix info window not showing after reattach

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java

feat: add click event listener to markers

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/KMLLayerDemo.java

Kml basic support

---

pom.xml

build: upgrade lombok to 1.18.24

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

build: update web component version to 3.2.1

---

README.md
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

Update web component version to 3.2.3.
Close #77

Update web component

---

src/test/java/com/flowingcode/vaadin/addons/googlemaps/AddMarkersDemo.java

fix(demo): avoid use of deprecated API

---

.gitignore
pom.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

Fix to prevent Roboto font from loading

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/RightClickOnMarkersDemo.java

feat: add right click event on markers

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

fix: use optimized property from the web-component

---

pom.xml
src/test/java/com/flowingcode/vaadin/addons/googlemaps/ClusteringWithCustomRendererDemo.java

Use new commons-demo version 3.9.0-SNAPSHOT that allows to add multiple sources to a demo.

Use multi souce on Clustering with Custom Renderer demo

---

pom.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java

* Update web component dependency to add new google-map-bounds_changed event when map bounds change (this upgrade it's needed to be able to merge #107)
* Update component version

Update web component dependency to add bounds change event

---

pom.xml
src/main/java/com/flowingcode/vaadin/addons/googlemaps/ControlPosition.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/CustomControl.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoint.java
src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPoly.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GeolocationDemo.java
src/test/resources/META-INF/resources/frontend/styles/google-maps/geolocation-demo-styles.css

Add support for adding custom control buttons

---

src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMap.java
src/main/resources/META-INF/resources/frontend/googlemaps/geolocation.js
src/test/java/com/flowingcode/vaadin/addons/googlemaps/GooglemapsDemoView.java
src/test/java/com/flowingcode/vaadin/addons/googlemaps/TrackLocationDemo.java

feat: add possibility to track location
